t statuname: polar
description: This is a Dart plugin wrapper for the Polar SDK on Android and iOS
version: 2.2.0
homepage: https://github.com/Rexios80/polar

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_plugin_android_lifecycle: ^2.0.5
  permission_handler: ^10.0.0
  device_info_plus: ^4.0.0
  recase: ^4.0.0
  transmogrify:
    hosted:  # https://dart.dev/tools/pub/dependencies#hosted-packages
      name: transmogrify
      url: https://some-package-server.com
    version: ^1.4.0
  hosted_dependency:
    path: ../hosted_dependency_patch/
  git_dependency:
    git:
      url: git@github.com:imsilly/git_dependency.git
      path: path/to/git_dependency_with_no_ref

dev_dependencies:
  flutter_test:
    sdk: flutter

  rexios_lints: ^3.0.0

dependency_overrides:  # https://dart.dev/tools/pub/dependencies#dependency-overrides
  recase: '5.2.1'

flutter:
  plugin:
    platforms:
      android:
        package: dev.rexios.polar
        pluginClass: PolarPlugin
      ios:
        pluginClass: PolarPlugin
